# https://gitlab.com/charts/auto-deploy-app/blob/master/values.yaml
# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
podAnnotations: {}
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
gitlab:
  app:
  env:
service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  url: http://my.host.com/
  additionalHosts:
  commonName:
  externalPort: 5000
  # Changed to our running Symfony app
  internalPort: 80
ingress:
  tls:
    enabled: false
    secretName: ""
  annotations:
    kubernetes.io/tls-acme: "false"
    kubernetes.io/ingress.class: "nginx"
livenessProbe:
  path: "/health"
  initialDelaySeconds: 15
  timeoutSeconds: 15
readinessProbe:
  path: "/health"
  initialDelaySeconds: 5
  timeoutSeconds: 3
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1

# https://github.com/helm/charts/blob/master/stable/mysql/values.yaml
mysql:
  persistence:
    enabled: false
